# Generated by Django 4.2.7 on 2026-06-25 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requirement_analysis', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('provider_type', models.CharField(choices=[('deepseek', 'DeepSeek'), ('qwen', '通义千问'), ('siliconflow', '硅基流动'), ('zhipu', '智谱'), ('xiaomi', '小米'), ('openai_compatible', 'OpenAI 兼容'), ('other', '其他')], max_length=30, verbose_name='模型提供商')),
                ('api_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='API Key')),
                ('base_url', models.URLField(verbose_name='API Base URL')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('max_tokens', models.IntegerField(default=4096, verbose_name='最大Token数')),
                ('temperature', models.FloatField(default=0.7, verbose_name='温度参数')),
                ('top_p', models.FloatField(default=0.9, verbose_name='Top P参数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': 'AI模型提供商',
                'verbose_name_plural': 'AI模型提供商',
                'db_table': 'ai_model_provider',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='requirement_analysis_buffer',
            field=models.TextField(blank=True, verbose_name='需求分析流式输出缓冲区'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='requirement_analysis_position',
            field=models.IntegerField(default=0, verbose_name='需求分析流式输出位置'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='requirement_analysis_result',
            field=models.TextField(blank=True, verbose_name='需求分析结果'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='requirement_analyzer_model_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_analyzer_tasks', to='requirement_analysis.aimodelconfig', verbose_name='需求分析模型配置'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='requirement_analyzer_prompt_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_analyzer_tasks', to='requirement_analysis.promptconfig', verbose_name='需求分析提示词配置'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='requirement_review_buffer',
            field=models.TextField(blank=True, verbose_name='需求评审流式输出缓冲区'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='requirement_review_position',
            field=models.IntegerField(default=0, verbose_name='需求评审流式输出位置'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='requirement_review_result',
            field=models.TextField(blank=True, verbose_name='需求评审结果'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='requirement_reviewer_model_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_reviewer_tasks', to='requirement_analysis.aimodelconfig', verbose_name='需求评审模型配置'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='requirement_reviewer_prompt_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_reviewer_tasks', to='requirement_analysis.promptconfig', verbose_name='需求评审提示词配置'),
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='role',
            field=models.CharField(choices=[('requirement_reviewer', '需求评审专家'), ('requirement_analyzer', '需求分析专家'), ('writer', '测试用例编写专家'), ('reviewer', '测试评审专家'), ('browser_use_text', 'Browser Use - 文本模式')], max_length=20, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='promptconfig',
            name='prompt_type',
            field=models.CharField(choices=[('requirement_reviewer', '需求评审提示词'), ('requirement_analyzer', '需求分析提示词'), ('writer', '用例编写提示词'), ('reviewer', '用例评审提示词')], max_length=20, verbose_name='提示词类型'),
        ),
        migrations.AlterField(
            model_name='testcasegenerationtask',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('reviewing_requirement', '需求评审中'), ('analyzing_requirement', '需求分析中'), ('generating', '用例生成中'), ('reviewing', '用例评审中'), ('revising', '改进中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=30, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='AIModelUsageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(choices=[('requirement_reviewer', '需求评审专家'), ('requirement_analyzer', '需求分析专家'), ('testcase_writer', '测试用例编写专家'), ('testcase_reviewer', '测试用例评审专家'), ('browser_use_text', 'Browser Use 文本模式'), ('browser_use_vision', 'Browser Use 视觉模式（预留）')], max_length=30, unique=True, verbose_name='用途类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('model_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_configs', to='requirement_analysis.aimodelprovider', verbose_name='关联模型')),
            ],
            options={
                'verbose_name': 'AI模型用途配置',
                'verbose_name_plural': 'AI模型用途配置',
                'db_table': 'ai_model_usage_config',
            },
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='requirement_analyzer_model_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_analyzer_tasks', to='requirement_analysis.aimodelprovider', verbose_name='需求分析模型配置'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='requirement_reviewer_model_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_reviewer_tasks', to='requirement_analysis.aimodelprovider', verbose_name='需求评审模型配置'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='reviewer_model_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_generation_tasks', to='requirement_analysis.aimodelprovider', verbose_name='用例评审模型配置'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='writer_model_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writer_generation_tasks', to='requirement_analysis.aimodelprovider', verbose_name='用例编写模型配置'),
        ),
    ]
